# Spring Boot application configuration
Spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/HealthCareSystemDemo

jwt:
    secret:

server:
    port: 8080
# Add other configuration as needed
